# -*- coding: utf-8 -*-
"""Numpy_array_creation2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10sAktRYcTSWhOEt7NjKOCGkVXJaHVnif
"""

import numpy as np

# 배열 만들기
a1 = np.array([1,2,3,4,5])
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
      [[1,2,3],[4,5,6,],[7,8,9]],
      [[1,2,3],[4,5,6],[7,8,9]]])

# 배열 생성 및 초기화

# 모든 요소를 0으로 초기화
np.zeros(10)

# 모든 요소를 1으로 초기화
np.ones(3)
np.ones([3,3])

# 모든 원소를 지정한 값으로 초기화
np.full((3,3), 1.23)

# 단위 행렬 생성
# 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬
np.eye(3)

# 삼각행렬
np.tri(3)

# 초기회되지 않은 배열 생성
np.empty(10)

# 저장된 배열과 shape가 같은 행렬 생성
np.zeros_like(a1)
np.zeros_like(a2)
np.zeros_like(a3)