# -*- coding: utf-8 -*-
"""Numpy_array_indexing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10sAktRYcTSWhOEt7NjKOCGkVXJaHVnif
"""

import numpy as np

# 배열 만들기
a1 = np.array([1,2,3,4,5])
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
      [[1,2,3],[4,5,6,],[7,8,9]],
      [[1,2,3],[4,5,6],[7,8,9]]])

# 인덱싱

print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])
print()

print(a2)
print(a2[0,0])
print(a2[0,2])
print(a2[1,1])
print(a2[2,-1])
print()

print(a3)
print(a3[0,0,0])
print(a3[1,1,1])
print(a3[2,2,2])
print(a3[2,-1,-1])