# -*- coding: utf-8 -*-
"""Numpy_array_creation2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10sAktRYcTSWhOEt7NjKOCGkVXJaHVnif
"""

import numpy as np

# 배열 만들기
a1 = np.array([1,2,3,4,5])
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
      [[1,2,3],[4,5,6,],[7,8,9]],
      [[1,2,3],[4,5,6],[7,8,9]]])

# 배열 생성 및 초기화

# 모든 요소를 0으로 초기화
np.zeros(10)

# 모든 요소를 1으로 초기화
np.ones(3)
np.ones([3,3])

# 모든 원소를 지정한 값으로 초기화
np.full((3,3), 1.23)

# 단위 행렬 생성
# 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬
np.eye(3)

# 삼각행렬
np.tri(3)

# 초기회되지 않은 배열 생성
np.empty(10)

# 저장된 배열과 shape가 같은 행렬 생성
np.zeros_like(a1)
np.zeros_like(a2)
np.zeros_like(a3)

# 생성한 값으로 배열 생성

# 정수 범위로 배열 생성
np.arange(0,30,2)

# 범위 내에서 균등한 간격의 배열 생성
np.linspace(0,1,5)

# 범위 내에서 균등한 간격으로 로그 스케일 배열 생성
np.logspace(0.1,1,20)

# 랜덤값으로 배열 생성

# 랜덤한 수의 배열 생성
np.random.random((3,3))

# 일정한 구간의 랜덤 정수의 배열 생성
np.random.randint(0,10,(3,3))

# 정규분포를 고려한 랜덤한 수의 배열 생성
# 평균 = 0, 표준편차=1, 3x3배열
np.random.normal(0,1,(3,3))

# 균등분포를 고려한 랜덤한 수의 배열 생성
np.random.rand(3,3)

# 표준 정규 분포를 고려한 랜덤한 수의 배열 생성
np.random.randn(3,3)